config/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls', namespace='menu')),
    path('__debug__/', include(debug_toolbar.urls)),
]

menu/urls.py
from django.urls import path
from menu.apps import MenuConfig
from menu.views import MenuListView, MenuDetailView

app_name = MenuConfig.name

urlpatterns = [
    path('', MenuListView.as_view(), name='menu_list'),
    path('menu/<int:pk>', MenuDetailView.as_view(), name='menu'),
]

menu/models.py
from django.db import models

from user.models import NULLABLE
# Анита

# Create your models here.


class Menu(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(**NULLABLE)
    soup = models.ManyToManyField('Soup', related_name='soup')
    main = models.ManyToManyField('Main', related_name='main')
    dessert = models.ManyToManyField('Dessert', related_name='dessert')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'меню'
        verbose_name_plural = 'меню'


class Soup(models.Model):
    title = models.CharField(max_length=100, verbose_name='название')
    ingredients = models.CharField(max_length=100, verbose_name='ингредиенты')
    allergens = models.CharField(max_length=100, **NULLABLE)
    description = models.TextField(**NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'суп'
        verbose_name_plural = 'супы'


class Main(models.Model):
    title = models.CharField(max_length=100, verbose_name='название')
    ingredients = models.CharField(max_length=100, verbose_name='ингредиенты')
    allergens = models.CharField(max_length=100, **NULLABLE)
    description = models.TextField(**NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'главное'
        verbose_name_plural = 'главные'


class Dessert(models.Model):
    title = models.CharField(max_length=100, verbose_name='название')
    ingredients = models.CharField(max_length=100, verbose_name='ингредиенты')
    allergens = models.CharField(max_length=100, **NULLABLE)
    description = models.TextField(**NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'десерт'
        verbose_name_plural = 'десерты'

user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'null': True, 'blank': True}


# Create your models here.
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

menu/views.py
from django.views.generic import ListView, DetailView
from menu.models import Menu


class MenuListView(ListView):
    """Страница со всеми меню"""

    model = Menu

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu_list'] = Menu.objects.prefetch_related('soup', 'main', 'dessert').all()
        return context


class MenuDetailView(DetailView):
    """Отображение единственного меню """
    model = Menu

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object_list'] = Menu.objects.filter(pk=self.object.pk)
        return context

menu/templates/menu/base.html
{% load static %}
<html lang="en" data-bs-theme="auto" xmlns="http://www.w3.org/1999/html">
  <head><script src="{% static 'js/color-modes.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/examples.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  </head>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
      body {
          background-image: url('{% static 'image/back.jpeg' %}');
          background-size: cover;
          background-repeat: no-repeat;
            }
      .nav-item .nav-link.active {
            background-color: orange;
            color: #000;
      }
      .nav-item .nav-link {
            background-color: grey;
            color: #111;
        }
      .btn-secondary {
              background-color: orange;
              color: white; /* Цвет текста на кнопке */
              border-color: white #your_color; /* Цвет рамки кнопки */
            }
      .btn-secondary:hover {
          background-color: red;
          border-color: white #your_hover_color; /* Цвет рамки кнопки при наведении */
          color: white; /* Цвет текста на кнопке */
        }


    </style>
    <main>
        <ul class="nav nav-pills nav-justified" id="pills-tab" role="tablist">
            <li class="nav-item" role="presentation">
                <a class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Главная</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-address-tab" data-bs-toggle="pill" href="#pills-address" role="tab" aria-controls="pills-address" aria-selected="false" >Наш адрес</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-contact-tab" data-bs-toggle="pill" href="#pills-contact" role="tab" aria-controls="pills-contact" aria-selected="false">О нас</a>
            </li>
            <li class="nav-item" role="presentation">
                <a class="nav-link" id="pills-events-tab" data-bs-toggle="pill" href="#pills-events" role="tab" aria-controls="pills-events" aria-selected="false">Предстоящие мероприятия</a>
            </li>
        </ul>

        <div class="container">
            <div class="row text-start">
                <div class=" mt-5 mb-5 text-start m-5">
                    <h5 class="card-title pricing-card-title"></h5>
                </div>
                 <div class="accordion" id="accordionPanelsStayOpenExample">
                    <div class="accordion-item">
                    {% block content %}

                    {% endblock content %}
                    </div>
                 </div>
            </div>
        </div>
    </main>

  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</html>

menu/templates/menu/menu_detail.html
{% extends 'menu/base.html' %}
{% block content %}
{% load static %}
  <style>

        .card {

            background-image: url('{% static 'image/3.jpg' %}');
            background-size: cover;
            background-repeat: no-repeat;
            padding: 20px; /* Можете указать необходимый отступ */
        }
        .card-body {
             color: rgb(0,0,0);

        }
    </style>
{% for  object in object_list %}
            <div class="card">
                <div class="card_header">
                    <h3 class="card-title pricing-card-title">{{ object.name }}</h3>
                </div>
                {% for position in object.main.all %}
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">{{ position.title }}</h4>
                    <h4 class="card-title pricing-card-title">{{ position.description }}</h4>
                    <h4 class="card-title pricing-card-title">{{ position.ingredients }}</h4>
                    <h4 class="card-title pricing-card-title">{{ position.allergens }}</h4>
                </div>
                {% endfor %}
                {% for position in object.soup.all %}
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">{{ position.title }}</h4>
                    <h4 class="card-title pricing-card-title">{{ position.description }}</h4>
                    <h4 class="card-title pricing-card-title">{{ position.ingredients }}</h4>
                    <h4 class="card-title pricing-card-title">{{ position.allergens }}</h4>
                </div>
                {% endfor %}
                {% for position in object.dessert.all %}
                <div class="card-body">
                    <h4 class="card-title pricing-card-title">{{ position.title }}</h4>
                    <h4 class="card-title pricing-card-title">{{ position.description }}</h4>
                    <h4 class="card-title pricing-card-title">{{ position.ingredients }}</h4>
                    <h4 class="card-title pricing-card-title">{{ position.allergens }}</h4>
                </div>
                {% endfor %}

            </div>
{% endfor %}


{% endblock content %}

menu/templates/menu/menu_list.html
{% extends 'menu/base.html' %}
{% block content %}
{% load static %}
    <style>
    .accordion-item {


    background-color: black;
    background-size: cover;
    background-repeat: no-repeat;
    }
    .accordion-body {
        color: white;
    }
    </style>
{% for object in object_list %}
    <h2 class="accordion-header">
        <button class="accordion-button btn-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse{{ object.pk }}" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
            {{ object.name }}
        </button>
    </h2>

    <div id="panelsStayOpen-collapse{{ object.pk }}" class="accordion-collapse collapse show">
        {% for position in object.main.all %}
            <div class="accordion-body">
                <a class="nav-link" href="{% url 'menu:menu' object.pk %}" aria-current="page">{{ position.title }}</a>
            </div>
        {% endfor %}
        {% for position in object.soup.all %}
            <div class="accordion-body">
                <a class="nav-link" href="{% url 'menu:menu' object.pk %}" aria-current="page">{{ position.title }}</a>
            </div>
        {% endfor %}
        {% for position in object.dessert.all %}
            <div class="accordion-body">
                <a class="nav-link" href="{% url 'menu:menu' object.pk %}" aria-current="page">{{ position.title }}</a>
            </div>
        {% endfor %}
    </div>
{% endfor %}

{% endblock content %}